-- Assumes table:
-- CREATE TABLE IF NOT EXISTS onc_drugs (
--   key text PRIMARY KEY,
--   data jsonb NOT NULL
-- );
BEGIN;
INSERT INTO onc_drugs(key, data) VALUES ('venetoclax', '{"key": "venetoclax", "names": ["Venetoclax", "베네토클락스", "Venclexta"], "class": "BCL-2 inhibitor", "indications": ["AML(비정상세포수↑ 동반/저메틸화요법 병합)", "CLL/SLL"], "common_AEs": ["오심/구토", "설사", "피로", "감염", "호중구감소"], "emergent_flags": ["TLS 위험(단계적 증량·수액·알로퓨리놀/라스부리카제)"], "contra": ["강력 CYP3A 억제제 병용 시 초기/증량 단계 금기"], "dose_notes": "CLL 기준 주당 단계적 증량 20→50→100→200→400 mg; AML 병용 시 프로토콜에 따름. 신부전/고요산혈증/고종양부하 시 입원 모니터.", "ddi": ["CYP3A 억/유도제", "P-gp 기질(디곡신 등) 주의"], "tips": ["증량 전 2–3일 전부터 수액·요산강하제 시작", "고위험군은 6–8h 간격으로 전해질 체크"], "monitor": {"baseline": ["Glucose: 공복혈당/당화혈색소(스테로이드 병용 시 변동)", "Lipids: 지질프로필(스테로이드·TKI 병용 시)", "LFT: 간기능(AST/ALT, bilirubin)", "Renal: Cr/eGFR", "Electrolytes: K, Ca, PO4, Mg", "Uric acid", "CBC/diff"], "during": ["TLS labs(6–8h 간격): Cr, K, Ca, PO4, uric acid", "CBC 주 1회(초기), 감염 증상 모니터", "LFT/QT 동시 위험 약제 병용 시 간헐 체크"], "extra": ["고종양부하군 입원 모니터 권장", "디곡신 병용 시 trough 관찰"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('gilteritinib', '{"key": "gilteritinib", "names": ["Gilteritinib", "길테리티닙", "Xospata"], "class": "FLT3 inhibitor", "indications": ["재발/불응 AML(FLT3 변이)"], "common_AEs": ["설사/변비", "피로", "간효소↑"], "emergent_flags": ["분화증후군", "QT 연장"], "contra": [], "dose_notes": "120 mg PO QD. 분화증후군 의심시 덱사메타손 10 mg IV q12h 즉시.", "ddi": ["강력 CYP3A 억제/유도제", "QT 연장 약물 병용 주의"], "tips": ["호흡곤란·발열·부종·저혈압 동반 시 분화증후군 의심"], "monitor": {"baseline": ["ECG: QTc", "Electrolytes: K, Mg", "LFT: AST/ALT, bilirubin", "CBC/diff"], "during": ["ECG: 시작 1주·월 1회(또는 용량/증상 변화 시)", "Electrolytes: K/Mg 주기적 보정", "분화증후군 증상 모니터"], "extra": ["QTc>500ms 시 일시중단/교정", "강력 CYP3A 억제제 병용 시 노출↑"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('midostaurin', '{"key": "midostaurin", "names": ["Midostaurin", "미도스타우린", "Rydapt"], "class": "멀티키나제/FLT3 inhibitor", "indications": ["초치료 AML(7+3와 병용, FLT3 변이)", "Systemic mastocytosis"], "common_AEs": ["오심/구토", "설사", "발진", "간효소↑"], "emergent_flags": ["QT 연장 드묾"], "contra": [], "dose_notes": "AML: Day8–21 동안 50 mg PO BID, 유도/공고 주기별 반복.", "ddi": ["CYP3A 억제/유도제 주의"], "tips": ["강한 오심 유발 → 투여 전 항구토제 권장"], "monitor": {"baseline": ["ECG: QTc", "LFT: AST/ALT, bilirubin", "CBC/diff"], "during": ["LFT: 주기적", "ECG/전해질: QT 위험약 병용 시"], "extra": ["위장관 AEs 관리: 항구토제·식후 복용"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('ivosidenib', '{"key": "ivosidenib", "names": ["Ivosidenib", "이보시데닙", "Tibsovo"], "class": "IDH1 inhibitor", "indications": ["AML(IDH1 변이)", "IDH1 변이 담도암"], "common_AEs": ["오심/설사", "백혈구↑", "피로"], "emergent_flags": ["분화증후군", "QT 연장 드묾"], "contra": [], "dose_notes": "500 mg PO QD. 분화증후군 시 덱사 10 mg IV q12h.", "ddi": ["CYP3A 기질/억제제 상호작용", "QT 연장 약물 주의"], "tips": ["백혈구 상승이 약효와 동반될 수 있음—감별 필요"], "monitor": {"baseline": ["ECG: QTc", "Electrolytes: K, Mg", "LFT: AST/ALT, bilirubin", "CBC/diff"], "during": ["ECG: 시작 1주·1개월 후·이후 주기적", "Electrolytes: 정기 보정", "분화증후군 증상 체크"], "extra": ["강력 CYP3A 억제제 병용 시 용량감소 고려"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('enasidenib', '{"key": "enasidenib", "names": ["Enasidenib", "에나시데닙", "Idhifa"], "class": "IDH2 inhibitor", "indications": ["재발/불응 AML(IDH2 변이)"], "common_AEs": ["오심/설사", "피로", "빌리루빈↑(UGT1A1 억제)"], "emergent_flags": ["분화증후군"], "contra": [], "dose_notes": "100 mg PO QD.", "ddi": ["UGT1A1 기질", "CYP 상호작용 가능"], "tips": ["빌리루빈 단독 상승은 약물기전과 관련될 수 있음"], "monitor": {"baseline": ["LFT: AST/ALT, bilirubin", "CBC/diff"], "during": ["LFT/CBC: 매주→매월", "분화증후군 증상 모니터"], "extra": ["중증 고빌리루빈혈증 시 용량조절"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('glasdegib', '{"key": "glasdegib", "names": ["Glasdegib", "글라스데깁", "Daurismo"], "class": "Hedgehog pathway inhibitor", "indications": ["고령/취약 AML(저강도요법 병합)"], "common_AEs": ["근육통/경련", "미각 변화", "오심/설사"], "emergent_flags": ["QT 연장"], "contra": [], "dose_notes": "100 mg PO QD, 저메틸화요법과 병용.", "ddi": ["CYP3A 상호작용", "QT 연장 약물 병용 주의"], "tips": ["근경련 예방에 전해질 보정·수분섭취"], "monitor": {"baseline": ["ECG: QTc", "Electrolytes: K, Mg", "LFT: AST/ALT, bilirubin"], "during": ["ECG: 시작 후 1주·1개월·이후 주기", "Electrolytes: 주기 보정"], "extra": ["QTc>500ms 시 중단/교정"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('azacitidine', '{"key": "azacitidine", "names": ["Azacitidine", "아자시티딘", "Vidaza"], "class": "Hypomethylating agent", "indications": ["MDS/CMML/AML(저강도)"], "common_AEs": ["골수억제", "오심/구토", "설사/변비", "주사부위 반응(SC)", "피로"], "emergent_flags": [], "contra": [], "dose_notes": "SC/IV 75 mg/m² x7일 q28d(표준). 반응 지연 가능—보통 ≥4–6주기 평가.", "ddi": [], "tips": ["초기 골수억제·감염 위험—G-CSF/항생제 전략 사전 계획"], "monitor": {"baseline": ["CBC/diff", "Renal: Cr/eGFR", "LFT: AST/ALT, bilirubin"], "during": ["CBC: 주당(초기)→주기별", "LFT/Cr: 각 주기 전"], "extra": ["주사부위 관리: 얼음찜질/교대 부위"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
INSERT INTO onc_drugs(key, data) VALUES ('decitabine', '{"key": "decitabine", "names": ["Decitabine", "데시타빈", "Dacogen"], "class": "Hypomethylating agent", "indications": ["MDS/AML(저강도)"], "common_AEs": ["골수억제", "오심/구토", "설사/변비", "피로"], "emergent_flags": [], "contra": [], "dose_notes": "20 mg/m² IV x5일 q28d 등 프로토콜별.", "ddi": [], "tips": ["반응까지 여러 주기 필요—치료 지속성 설명"], "monitor": {"baseline": ["CBC/diff", "Renal: Cr/eGFR", "LFT: AST/ALT, bilirubin"], "during": ["CBC: 주당(초기)→주기별", "LFT/Cr: 각 주기 전"], "extra": ["감염 예방 전략(예: 항바이러스/항진균 고위험군)"]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET data = EXCLUDED.data;
COMMIT;
